name: Gyisti Production
title: Gyisti Production
description: making the some mods, resource packs, websites, games and etc.
url: gyisti.github.io
collections:
  posts:
    output: true

encoding: "utf-8"

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  

webrick:
  headers:
    testing: test
